### ISSUE TITLE
Cant open any files

### ISSUE THREAD

**Issue by gale9010** [adesandr/GliderThrow_Meter#1]
Hi, i can´t open any files, i try with arduino ide and visual studio code and i can´t see the code for upload to esp32. 
Can you explain how i did upload the code to try this project¿?

**Comment by adesandr** [comment]
Hello, sorry to be late in my answer.
This project is developed using the ESP-IDF 4.0 framework and VScode IDE, and can't be used with the arduino IDE.
Refer to https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/index.html for more information on ESP-IDF framework and How to install.
Refer also to https://marketplace.visualstudio.com/items?itemName=espressif.esp-idf-extension to add the new Espressif IOT Extenssion to Vscode.
