### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by neffets88** [adesandr/GliderThrow_Meter#4]
Hi @adesandr 
First of all thank you for sharing your work with the world :)
Are there any plans on upgrading to 4 Sensors? I mostly fly F3B gliders with 2 control surfaces per wing an up to 7 Flight Phases. Setting the throws would become much easier with 4 Sensors at a time.
Greetings
Steffen

**Comment by adesandr** [comment]
Hi,
Thanks for your support.
Yes, this feature is plan for 2022, without precise date for the moment (unfortunatly too few time to fly and to devellop :-(.
Regards.

Alain Désandré
Mob : +33 6 84 54 40 12
